services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=<password> #optional
      - HASHED_PASSWORD=<password> #optional
      - SUDO_PASSWORD=<password> #optional
      - SUDO_PASSWORD_HASH=<password> #optional
      - PROXY_DOMAIN=codeserver.domain.tld #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /path/to/file/codeserver/config:/config
    ports:
      - <port>:443
    restart: unless-stopped