services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_ADMIN_USER=<username>
      - PAPERLESS_ADMIN_PASSWORD=<password>
      - PAPERLESS_ALLOWED_HOSTS=paperless.domain.tld
      - PAPERLESS_URL=https://paperless.domain.tld
    volumes:
      - /path/to/file/paper/config:/config
      - /path/to/file/paper/data:/data
    ports:
      - <port>:80
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis