services:
  navidrome:
    container_name: navi
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "<port>:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_IMAGECACHESIZE: 0
      ND_COVERARTPRIORITY: "cover.*, folder.*, embedded"
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "https://domain.tld"
    volumes:
      - "/path/to/music/navi:/data"
      - "/path/to/music:/music:ro"  