# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: A random homepage
description: Yo
theme: dark
disableCollapse: true
color: purple
uptime: true
hideVersion: true
useEqualHeights: true
headerStyle: boxedWidgets
favicon: image
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom

background:
  image: image/gif
  backdrop-filter: blur(1px);
  backdrop-opacity: 100
  saturate: 47 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 77 # 0-100